// web/src/pages/builds.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import { Table } from 'patternfly-react'

import { fetchBuilds } from '../api'

class BuildsPage extends React.Component {
  constructor () {
    super()

    this.state = {
      builds: []
    }
  }

  componentDidMount () {
    fetchBuilds().then(response => {
      this.setState({builds: response.data})
    })
  }
  render () {
    const { builds } = this.state
    if (builds.length === 0) {
      return (<p>Loading...</p>)
    }
    const headerFormat = value => <Table.Heading>{value}</Table.Heading>
    const cellFormat = (value) => (
      <Table.Cell>{value}</Table.Cell>)
    /*
     * For info about noopener noreferrer, see
     * https://mathiasbynens.github.io/rel-noopener/
     */
    const linkCellFormat = (value) => (
      <Table.Cell>
        <a href={value} target="_blank" rel="noopener noreferrer">link</a>
      </Table.Cell>
    )
    const columns = []
    const myColumns = [
      'job',
      'project',
      'branch',
      'pipeline',
      'change',
      'duration',
      'log',
      'start time',
      'result']
    myColumns.forEach(column => {
      let prop = column
      let formatter = cellFormat
      // Adapt column name and property name
      if (prop === 'job') {
        prop = 'job_name'
      } else if (prop === 'start time') {
        prop = 'start_time'
      } else if (prop === 'change') {
        prop = 'ref_url'
        formatter = linkCellFormat
      } else if (prop === 'log') {
        prop = 'log_url'
        formatter = linkCellFormat
      }
      columns.push({
        header: {label: column.charAt(0).toUpperCase() + column.slice(1),
          formatters: [headerFormat]},
        property: prop,
        cell: {formatters: [formatter]}
      })
    })
    return (
      <Table.PfProvider
        striped
        bordered
        columns={columns}
      >
        <Table.Header/>
        <Table.Body
          rows={builds}
          rowKey="uuid"
          onRow={(row) => {
            switch (row.result) {
              case 'SUCCESS':
                return { className: 'success' }
              default:
                return { className: 'warning' }
            }
          }} />
      </Table.PfProvider>)
  }
}

export default BuildsPage

// web/builds/builds.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'
import { HttpClient, HttpParams } from '@angular/common/http'
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/map'

import getSourceUrl from '../util'
import Build from './build'


@Component({
  template: require('./builds.component.html')
})
export default class BuildsComponent implements OnInit {
  builds: Build[]
  pipeline: string
  job_name: string
  project: string
  tenant: string

  constructor(private http: HttpClient, private route: ActivatedRoute) {}

  ngOnInit() {

    this.tenant = this.route.snapshot.paramMap.get('tenant')

    this.pipeline = this.route.snapshot.queryParamMap.get('pipeline')
    this.job_name = this.route.snapshot.queryParamMap.get('job_name')
    this.project = this.route.snapshot.queryParamMap.get('project')

    this.buildsFetch()
  }

  buildsFetch(): void  {
    let params = new HttpParams()
    if (this.pipeline) { params = params.set('pipeline', this.pipeline) }
    if (this.job_name) { params = params.set('job_name', this.job_name) }
    if (this.project) { params = params.set('project', this.project) }

    const remoteLocation = getSourceUrl('builds', this.tenant)
    this.http.get<Build[]>(remoteLocation, {params: params})
      .subscribe(builds => { this.builds = builds })
  }
}

<!--
Copyright 2017 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <span style="float: right; margin-top: 7px;">
    <form #buildsForm="ngForm">
      <label for="pipeline">Pipeline:</label>
      <input id="pipeline" [(ngModel)]="pipeline" name="pipeline" />
      <label for="job_name">Job:</label>
      <input id="job_name" [(ngModel)]="job_name" name="job_name" />
      <label for="project">Project:</label>
      <input id="project" [(ngModel)]="project" name="project">
      <button type="submit" class="btn btn-success" (click)='buildsFetch()'>
          Refresh
      </button>
    </form>
  </span>
</div>
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Job</th>
      <th>Project</th>
      <th>Branch</th>
      <th>Pipeline</th>
      <th>Change</th>
      <th>Duration</th>
      <th>Log url</th>
      <th>Start time</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let build of builds" [class]="getRowClass(build)">
      <td>{{ build.job_name }}</td>
      <td>{{ build.project }}</td>
      <td>{{ build.branch }}</td>
      <td>{{ build.pipeline }}</td>
      <td><a href="{{ build.ref_url }}" target="_self">change</a></td>
      <td>{{ build.duration }} seconds</td>
      <td><a *ngIf="build.log_url" href="{{ build.log_url }}" target="_self">logs</a></td>
      <td>{{ build.start_time }}</td>
      <td>{{ build.result }}</td>
    </tr>
  </tbody>
</table>
