// web/src/pages/stream.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react';

class StreamPage extends React.Component {
  render() {
    return (<p>TODO: stream the build {this.props.match.params.buildId}</p>)
  }
}
export default StreamPage;

// web/stream/stream.component.ts
// @licstart  The following is the entire license notice for the
// JavaScript code in this page.
//
// Copyright 2018 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// @licend  The above is the entire license notice
// for the JavaScript code in this page.

import { Component, OnInit } from '@angular/core'

import zuulStartStream from './zuulStartStream'

@Component({
  template: require('./stream.html')
})
export default class StreamComponent implements OnInit {
  ngOnInit() {
    zuulStartStream()
  }
}

<!--
Copyright 2017 BMW Car IT GmbH

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
    <span id="zuulstreamoverlay">
        <form #streamForm="ngForm">
            <input id="autoscroll" [ngModel]="autoscroll" type="checkbox">
            autoscroll
        </form>
    </span>
</div>

<pre id="zuulstreamcontent">
  <span *ngFor="let line of logLines">{{ line }}</span>
</pre>
