// web/src/pages/Project.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'
import { PageSection, PageSectionVariants } from '@patternfly/react-core'

import Project from '../containers/project/Project'
import { fetchProjectIfNeeded } from '../actions/project'
import { Fetching } from '../containers/Fetching'


class ProjectPage extends React.Component {
  static propTypes = {
    match: PropTypes.object.isRequired,
    tenant: PropTypes.object,
    remoteData: PropTypes.object,
    dispatch: PropTypes.func
  }

  updateData = (force) => {
    this.props.dispatch(fetchProjectIfNeeded(
      this.props.tenant, this.props.match.params.projectName, force))
  }

  componentDidMount () {
    document.title = 'Zuul Project | ' + this.props.match.params.projectName
    this.updateData()
  }

  render () {
    const { remoteData } = this.props
    if (remoteData.isFetching) {
      return <Fetching />
    }

    const tenantProjects = remoteData.projects[this.props.tenant.name]
    const projectName = this.props.match.params.projectName
    return (
      <PageSection variant={PageSectionVariants.light}>
        {tenantProjects && tenantProjects[projectName] &&
         <Project project={tenantProjects[projectName]} />}
      </PageSection>
    )
  }
}

export default connect(state => ({
  tenant: state.tenant,
  remoteData: state.project,
}))(ProjectPage)

// web/project/project.component.ts
// Copyright 2018 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'
import { HttpClient, HttpParams } from '@angular/common/http'
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/map'

import ZuulService from '../zuul/zuul.service'
import Job from '../jobs/job'

interface Pipeline {
  name: string,
  queue_name: string,
  jobs: Job[]
}

interface ProjectDetail {
  project_name: string
  canonical_name: string
  default_branch: string
  merge_mode: string
  pipelines: Pipeline[]
}

@Component({
  template: require('./project.component.html')
})
export default class ProjectComponent implements OnInit {

  project_name: string
  project: ProjectDetail

  constructor(
    private http: HttpClient, private route: ActivatedRoute,
    private zuul: ZuulService
  ) {}

  async ngOnInit() {
    await this.zuul.setTenant(this.route.snapshot.paramMap.get('tenant'))
    this.project_name = this.route.snapshot.queryParamMap.get('project_name')

    this.projectFetch()
  }

  projectFetch(): void {
    const remoteLocation = this.zuul.getSourceUrl(
      'project/' + this.project_name)
    if (remoteLocation) {
      this.http.get<ProjectDetail>(remoteLocation)
        .subscribe(project => { this.project = project })
    }
  }
}

<!--
Copyright 2018 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <div class="container-fluid panel-group">
    <div class="panel panel-info">
      <div class="panel-heading">Project {{ project_name }}</div>
      <div class="panel panel-body">
        <table class="table table-condensed table-bordered">
          <tr>
            <td>Canonical name</td>
            <td>{{ project.canonical_name }}</td>
          </tr>
          <tr>
            <td>Connection name</td>
            <td>{{ project.connection_name }}</td>
          </tr>
        </table>
      </div>
    </div>
    <div class="panel panel-info" *ngFor="let config of project.configs">
      <div class="panel-heading">Configuration</div>
      <div class="panel panel-body">
        <table class="table table-condensed table-bordered">
          <tr>
            <td>Default branch</td>
            <td>{{ config.default_branch }}</td>
          </tr>
          <tr>
            <td>Merge mode</td>
            <td>{{ config.merge_mode }}</td>
          </tr>
        </table>
        <div class="panel panel-info"><div class="panel-heading">Pipelines</div>
        <div class="panel panel-body">
          <div *ngFor="let pipeline of config.pipelines">
            <h3>{{ pipeline.name }}</h3>
            <ul class="list-group">
              <li class="list-group-item" *ngFor="let job of pipeline.jobs">
                <a [routerLink]="['../job.html']"
                   [queryParams]="{job_name: job[0].name }" target="_self">
                    {{ job[0].name }}</a>
              </li>
            </ul>
          </div>
        </div></div>
      </div>
    </div>
  </div>
</div>
