// web/src/pages/Jobs.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { I18n } from 'react-redux-i18n'

import { fetchJobsIfNeeded } from '../actions/jobs'
import Refreshable from '../containers/Refreshable'
import Jobs from '../containers/jobs/Jobs'


class JobsPage extends Refreshable {
  static propTypes = {
    tenant: PropTypes.object,
    remoteData: PropTypes.object,
    dispatch: PropTypes.func
  }

  updateData (force) {
    this.props.dispatch(fetchJobsIfNeeded(this.props.tenant, force))
  }

  componentDidMount () {
    document.title = I18n.t('jobsPage.title')
    super.componentDidMount()
  }

  render () {
    const { remoteData } = this.props
    const jobs = remoteData.jobs[this.props.tenant.name]
    return (
      <React.Fragment>
        <div style={{float: 'right'}}>
          {this.renderSpinner()}
        </div>
        {jobs && jobs.length > 0 &&
          <Jobs
              jobs={jobs}
              />}
      </React.Fragment>)
  }
}

export default connect(state => ({
  tenant: state.tenant,
  remoteData: state.jobs,
}))(JobsPage)

// web/jobs/jobs.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { HttpClient } from '@angular/common/http'

import getSourceUrl from '../util'
import JobDetails from './details'
import Job from './job'

@Component({
  template: require('./jobs.component.html')
})
export default class JobsComponent implements OnInit {

  jobs: Job[]

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.jobsFetch()
  }

  jobsFetch(): void {
    console.log('blert')
    this.http.get<Job[]>(getSourceUrl('jobs')).subscribe(
      jobs => this.injestJobs(jobs))
  }

  injestJobs(jobs: Job[]): void {
    for (const job of jobs) {
      job.expanded = false
    }
    this.jobs = jobs
  }

  jobToggleExpanded(job: Job) {
    if (!job.details) {
      this.http.get<JobDetails>(getSourceUrl('jobs/' + job.name))
        .subscribe(details => {job.details = details})
    }
    job.expanded = !job.expanded
  }
}

<!--
Copyright 2017 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<button type="button" class="pull-right btn-xs btn-primary btn" (click)="toggleGraph()">
  Toggle graph
</button>
<div style="margin: auto; text-align: center; width: 100%">
  <svg width="1400" height="1060" id="jobGraph" style="display: none; text-align: center" />
</div>
<div class="container-fluid">
  <table class="table table-hover table-condensed" id="jobTable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Context</th>
        <th>Last builds</th>
      </tr>
    </thead>
    <tbody>
      <ng-container *ngFor="let job of jobs">
        <tr>
          <td><a [routerLink]="['../job.html']"
                 [queryParams]="{job_name: job.name}" target="_self">
              {{ job.name }}</a></td>
          <td>{{ job.description }}</td>
          <td><a (click)="jobToggleExpanded(job)">locations</a></td>
          <td><a [routerLink]="['../builds.html']"
                 [queryParams]="{job_name: job.name}" target="_self">
              builds</a></td>
        </tr>
        <tr *ngIf="job.expanded">
          <td colspan="3">
            <ul class="list-group">
              <li class="list-group-item" *ngFor="let detail of job.details">
                <!-- TODO: make clickable link to cgit files ? -->
                {{ detail.source_context.project }}: {{ detail.source_context.path }}@{{ detail.source_context.branch }}
              </li>
            </ul>
          </td>
        </tr>
      </ng-container>
    </tbody>
  </table>
</div>
