// web/src/containers/jobs/Jobs.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'
import { TreeView } from 'patternfly-react'


class JobsList extends React.Component {
  static propTypes = {
    tenant: PropTypes.object,
    jobs: PropTypes.array,
  }

  render () {
    const { jobs } = this.props

    const linkPrefix = this.props.tenant.linkPrefix + '/job/'

    // nodes contains the tree data
    const nodes = []
    // visited contains individual node
    const visited = {}
    // getNode returns the tree node and visit each parents
    const getNode = function (job) {
      if (!visited[job.name]) {
        // Collect parents
        let parents = []
        if (job.variants) {
          for (let jobVariant of job.variants) {
            if (jobVariant.parent) {
                parents.push(jobVariant.parent)
            }
          }
        }
        // Visit parent recursively
        for (let parent of parents) {
           for (let otherJob of jobs) {
            if (parent === otherJob.name) {
              getNode(otherJob)
              break
            }
          }
        }
        visited[job.name] = {
          text: (
            <React.Fragment>
              <Link to={linkPrefix + job.name}>{job.name}</Link>
              {job.description && (
                <span style={{marginLeft: '10px'}}>{job.description}</span>
              )}
            </React.Fragment>),
          icon: 'fa fa-cube',
          state: {
            expanded: true,
          },
          parents: parents,
        }
      }
      return visited[job.name]
    }
    // process job list
    for (let job of jobs) {
      const jobNode = getNode(job)
      let attached = false
      // add tree node to each parent and expand the parent
      for (let parent of jobNode.parents) {
        const parentNode = visited[parent]
        if (!parentNode) {
          console.log('Job ', job.name, ' parent ', parent, ' does not exist!')
          continue
        }
        if (!parentNode.nodes) {
          parentNode.nodes = []
        }
        parentNode.nodes.push(jobNode)
        attached = true
      }
      // else add node at the tree root
      if (!attached || jobNode.parents.length === 0) {
        nodes.push(jobNode)
      }
    }
    return (
      <div className='tree-view-container'>
        <TreeView nodes={nodes} />
      </div>
    )
  }
}

export default connect(state => ({
  tenant: state.tenant,
}))(JobsList)

// web/jobs/jobs.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { HttpClient } from '@angular/common/http'
import { ActivatedRoute } from '@angular/router'

import getSourceUrl from '../util'
import JobDetails from './details'
import Job from './job'

@Component({
  template: require('./jobs.component.html')
})
export default class JobsComponent implements OnInit {

  jobs: Job[]
  tenant?: string

  constructor(private http: HttpClient, private route: ActivatedRoute) {}

  ngOnInit() {
    this.tenant = this.route.snapshot.paramMap.get('tenant')
    this.jobsFetch()
  }

  jobsFetch(): void {
    console.log('blert')
    this.http.get<Job[]>(getSourceUrl('jobs'), this.tenant).subscribe(
      jobs => this.injestJobs(jobs))
  }

  injestJobs(jobs: Job[]): void {
    for (const job of jobs) {
      job.expanded = false
    }
    this.jobs = jobs
  }

  jobToggleExpanded(job: Job) {
    if (!job.details) {
      this.http.get<JobDetails>(getSourceUrl('jobs/' + job.name, this.tenant))
        .subscribe(details => {job.details = details})
    }
    job.expanded = !job.expanded
  }
}

<!--
Copyright 2017 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<button type="button" class="pull-right btn-xs btn-primary btn" (click)="toggleGraph()">
  Toggle graph
</button>
<div style="margin: auto; text-align: center; width: 100%">
  <svg width="1400" height="1060" id="jobGraph" style="display: none; text-align: center" />
</div>
<div class="container-fluid">
  <table class="table table-hover table-condensed" id="jobTable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Context</th>
        <th>Last builds</th>
      </tr>
    </thead>
    <tbody>
      <ng-container *ngFor="let job of jobs">
        <tr>
          <td><a [routerLink]="['../job.html']"
                 [queryParams]="{job_name: job.name}" target="_self">
              {{ job.name }}</a></td>
          <td>{{ job.description }}</td>
          <td><a (click)="jobToggleExpanded(job)">locations</a></td>
          <td><a [routerLink]="['../builds.html']"
                 [queryParams]="{job_name: job.name}" target="_self">
              builds</a></td>
        </tr>
        <tr *ngIf="job.expanded">
          <td colspan="3">
            <ul class="list-group">
              <li class="list-group-item" *ngFor="let detail of job.details">
                <!-- TODO: make clickable link to cgit files ? -->
                {{ detail.source_context.project }}: {{ detail.source_context.path }}@{{ detail.source_context.branch }}
              </li>
            </ul>
          </td>
        </tr>
      </ng-container>
    </tbody>
  </table>
</div>
