// web/job/job.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'
import { HttpClient } from '@angular/common/http'

import getSourceUrl from '../util'
import Variant from './variant'

@Component({
  template: require('./job.component.html')
})
export default class JobComponent implements OnInit {

  job_name: string
  job_url: string
  labels_color: Map<string, string>
  variants: Variant[]

  constructor(private http: HttpClient, private route: ActivatedRoute) {}

  ngOnInit() {
    this.job_name = this.route.snapshot.queryParamMap.get('job_name') || 'base'
    this.job_url = getSourceUrl('jobs/' + this.job_name)
    this.labels_color = new Map<string, string>()
    this.variants = undefined
    this.jobFetch()
  }

  jobFetch(): void {
    this.http.get<Variant[]>(this.job_url)
      .subscribe(variants => this.injestResults(variants))
  }

  injestResults(variants: Variant[]): void {
    for (const variant of variants) {
      if (Object.keys(variant.variables).length === 0) {
        variant.variables = undefined
      } else {
        variant.variables = JSON.stringify(
          variant.variables, undefined, 2)
      }
      if (variant.nodeset.length >= 0) {
        // Generate color based on node label
        for (const node of variant.nodeset) {
          let hash = 0
          for (let idx = 0; idx < node[0].length; idx++) {
            const c = node[0].charCodeAt(idx)
            hash = ((hash << 5) - hash) + c
          }
          const r = (0x800000 + (hash - 0x500000)) & 0xFF0000
          const g = (0x005000 + (hash - 0x00a000)) & 0x00FF00
          const b = (0x000080 + (hash - 0x50)) & 0x0000FF
          this.labels_color[node[0]] = '#' + (r | g | b).toString(16)
        }
      }
      if (variant.parent === 'None') {
        variant.parent = 'base'
      }
    }
    this.variants = variants
  }
}

<!--
Copyright 2018 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <div class="container-fluid panel-group">
    <div class="panel panel-info" *ngFor="let variant of variants">
      <div class="panel-heading">{{ job_name }}: {{ variant.source_context.project }}: {{ variant.source_context.path }}@{{ variant.source_context.branch }}</div>
      <div class="panel panel-body">
        <table class="table table-condensed table-bordered">
          <tr *ngIf="variant.description">
            <td>Description</td>
            <td style="white-space: pre;">{{ variant.description }}</td>
          </tr>
          <tr *ngIf="variant.variant_description">
            <td>Variant Description</td>
            <td>{{ variant.variant_description }}</td>
          </tr>
          <tr *ngIf="variant.parent">
            <td>Parent</td>
            <td><a [routerLink]="['../job.html']"
                   [queryParams]="{job_name: variant.parent}" target="_self">
                {{ variant.parent }}</a></td>
          </tr>
          <tr *ngIf="variant.branches">
            <td>Branches</td>
            <td>{{ variant.branches }}</td>
          </tr>
          <tr *ngIf="variant.post_review">
            <td>Post_Review</td>
            <td>{{ variant.post_review }}</td>
          </tr>
          <tr *ngIf="variant.voting">
            <td>Voting</td>
            <td>{{ variant.voting }}</td>
          </tr>
          <tr *ngIf="variant.final">
            <td>Final</td>
            <td>{{ variant.final }}</td>
          </tr>
          <tr *ngIf="variant.timeout">
            <td>Timeout</td>
            <td>{{ variant.timeout }}</td>
          </tr>
          <tr *ngIf="variant.attempts">
            <td>Attempts</td>
            <td>{{ variant.attempts }}</td>
          </tr>
          <tr *ngIf="variant.dependencies">
            <td>Job dependencies</td>
            <td>
              <ul class="list-unstyled">
                <li *ngFor="let dependency of variant.dependencies">
                  {{ dependency }}
                </li>
              </ul>
            </td>
          </tr>
          <tr *ngIf="variant.required_projects">
            <td>Required projects</td>
            <td>
              <ul class="list-unstyled">
                <li *ngFor="let project of variant.required_projects">
                  {{ project.canonical_name }}
                </li>
              </ul>
            </td>
          </tr>
          <tr *ngIf="variant.semaphore">
            <td>Semaphore</td>
            <td>{{ variant.semaphore }}</td>
          </tr>
          <tr *ngIf="variant.variables">
            <td>Variables</td>
            <td style="white-space: pre;">{{ variant.variables }}</td>
          </tr>
          <tr *ngIf="variant.roles">
            <td>Roles</td>
            <td>
              <ul class="list-unstyled">
                <li *ngFor="let role of variant.roles">
                  {{ role.target_name }} ({{ role.project_canonical_name }})
                </li>
              </ul>
            </td>
          </tr>
          <tr *ngIf="variant.nodeset && variant.nodeset.nodes">
            <td>Nodeset</td>
            <td>
              <ul class="list-inline"><li *ngFor="let node of variant.nodeset.nodes">
                <span [style]="getNodeLabelStyle(node)">
                  {{ node.label }}</span>
                <span>{{ node.name }}</span>
              </li></ul>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

// web/src/pages/Job.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'
import { PageSection, PageSectionVariants } from '@patternfly/react-core'

import Job from '../containers/job/Job'
import { Fetching } from '../containers/Fetching'
import { fetchJobIfNeeded } from '../actions/job'


class JobPage extends React.Component {
  static propTypes = {
    match: PropTypes.object.isRequired,
    tenant: PropTypes.object,
    remoteData: PropTypes.object,
    dispatch: PropTypes.func
  }

  updateData = (force) => {
    this.props.dispatch(fetchJobIfNeeded(
      this.props.tenant, this.props.match.params.jobName, force))
  }

  componentDidMount () {
    document.title = 'Zuul Job | ' + this.props.match.params.jobName
    this.updateData()
  }

  componentDidUpdate (prevProps) {
    if (this.props.tenant.name !== prevProps.tenant.name ||
       this.props.match.params.jobName !== prevProps.match.params.jobName) {
      this.updateData()
    }
  }

  render () {
    const { remoteData } = this.props
    if (remoteData.isFetching) {
      return <Fetching />
    }

    const tenantJobs = remoteData.jobs[this.props.tenant.name]
    const jobName = this.props.match.params.jobName
    return (
      <PageSection variant={PageSectionVariants.light}>
        {tenantJobs && tenantJobs[jobName] && <Job job={tenantJobs[jobName]} />}
      </PageSection>
    )
  }
}

export default connect(state => ({
  tenant: state.tenant,
  remoteData: state.job,
}))(JobPage)
