// web/nodes/nodes.component.ts
// Copyright 2018 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'
import { HttpClient, HttpParams } from '@angular/common/http'
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/map'

import ZuulService from '../zuul/zuul.service'

interface ZuulNode {
  name: string
}

@Component({
  template: require('./nodes.component.html')
})
export default class NodesComponent implements OnInit {

  nodes: ZuulNode[]
  tenant?: string

  constructor(
    private http: HttpClient, private route: ActivatedRoute,
    private zuul: ZuulService
  ) {}

  ngOnInit() {
    this.tenant = this.route.snapshot.paramMap.get('tenant')

    this.nodesFetch()
  }

  nodesFetch(): void {
    this.http.get<ZuulNode[]>(
      this.zuul.getSourceUrl('nodes', this.tenant))
      .subscribe(nodes => { this.nodes = nodes})
  }
}

<!--
Copyright 2018 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <table class="table table-hover table-condensed" id="nodesTable">
    <thead>
      <tr>
        <th>ID</th>
        <th>Label</th>
        <th>Connection</th>
        <th>Server ID</th>
        <th>Provider</th>
        <th>State</th>
        <th>Age</th>
        <th>Comment</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let node of nodes">
        <td>{{ node.id }}</td>
        <td>{{ node.type }}</td>
        <td>{{ node.connection_type }}</td>
        <td>{{ node.external_id }}</td>
        <td>{{ node.provider }}</td>
        <td>{{ node.state }}</td>
        <td>{{ node.age }}</td>
        <td>{{ node.comment }}</td>
      </tr>
    </tbody>
  </table>
</div>

// web/src/pages/Nodes.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'

import {
  ClusterIcon,
  InfrastructureIcon,
  KeyIcon,
  NetworkIcon,
  OutlinedCalendarAltIcon,
  OutlinedCommentsIcon,
  RunningIcon,
  TagIcon
} from '@patternfly/react-icons'

import * as moment from 'moment'

import { fetchNodesIfNeeded } from '../actions/nodes'
import {PageSection, PageSectionVariants} from '@patternfly/react-core'
import SortTable from '../containers/SortTable'

class NodesPage extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      fetching: false
    }
  }

  static propTypes = {
    tenant: PropTypes.object,
    remoteData: PropTypes.object,
    dispatch: PropTypes.func
  }

  updateData = (force) => {
    this.props.dispatch(fetchNodesIfNeeded(this.props.tenant, force))
  }

  componentDidMount() {
    document.title = 'Zuul Nodes'
    if (this.props.tenant.name) {
      this.updateData()
    }
  }

  componentDidUpdate(prevProps) {
    if (this.props.tenant.name !== prevProps.tenant.name) {
      this.updateData()
    }
  }

  render() {
    const nodes = this.props.remoteData.nodes
    const building = nodes.filter(n => n.state === 'building').length
    const ready = nodes.filter(n => n.state === 'ready').length
    const inUse = nodes.filter(n => n.state === 'in-use').length
    const deleting = nodes.filter(n => n.state === 'deleting').length

    return (
      <PageSection variant={PageSectionVariants.light}>
        <div style={{marginBottom: 10}}>
          <div>
            <b>Summary
              : </b>{nodes.length} total, {building} building, {ready} ready, {inUse} in-use, {deleting} deleting
          </div>
        </div>
        <SortTable
          defaultSort={'asc'}
          defaultSortIndex={1}
          config={[
            {
              name: 'Id',
              sortable: false,
              icon: <KeyIcon/>,
              field: 'id',
              formatters: []
            },
            {
              name: 'Label',
              sortable: true,
              icon: <TagIcon/>,
              field: 'type',
              formatters: []
            },
            {
              name: 'Connection',
              sortable: false,
              icon: <NetworkIcon/>,
              field: 'connection_type',
              formatters: []
            },
            {
              name: 'Server',
              sortable: true,
              icon: <ClusterIcon/>,
              field: 'external_id',
              formatters: []
            },
            {
              name: 'Provider',
              sortable: true,
              icon: <InfrastructureIcon/>,
              field: 'provider',
              formatters: []
            },
            {
              name: 'State',
              sortable: true,
              icon: <RunningIcon/>,
              field: 'state',
              formatters: []
            },
            {
              name: 'Age',
              sortable: true,
              icon: <OutlinedCalendarAltIcon/>,
              field: 'state_time',
              formatters: [date => (moment.unix(date).fromNow())]
            },
            {
              name: 'Comment',
              sortable: false,
              icon: <OutlinedCommentsIcon/>,
              field: 'comment',
              formatters: []
            }
          ]}
          data={nodes}
          name={'Nodes Table'}/>
      </PageSection>
    )
  }
}

export default connect(state => ({
  tenant: state.tenant,
  remoteData: state.nodes,
}))(NodesPage)
