// web/projects/projects.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'
import { HttpClient, HttpParams } from '@angular/common/http'

import getSourceUrl from '../util'

interface Project {
  name: string
  type: string
}

@Component({
  template: require('./projects.component.html')
})
export default class ProjectsComponent implements OnInit {

  projects: Project[]

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.projectsFetch()
  }

  projectsFetch(): void {
    this.http.get<Project[]>(getSourceUrl('projects'))
      .subscribe(projects => { this.projects = projects})
  }
}

<!--
Copyright 2017 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <table class="table table-hover table-condensed" id="projectTable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Connection</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let project of projects">
        <td><a [routerLink]="['../project.html']"
               [queryParams]="{project_name: project.canonical_name}" target="_self">
                {{ project.name }}</a></td>
        <td>{{ project.connection_name }}</td>
        <td>{{ project.type }}</td>
      </tr>
    </tbody>
  </table>
</div>

// web/src/pages/Projects.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'
import { Table } from 'patternfly-react'

import { fetchProjects } from '../api'


class ProjectsPage extends React.Component {
  static propTypes = {
    tenant: PropTypes.object
  }

  state = {
    projects: null
  }

  updateData () {
    fetchProjects(this.props.tenant.apiPrefix).then(response => {
      this.setState({projects: response.data})
    })
  }

  componentDidMount () {
    document.title = 'Zuul Projects'
    if (this.props.tenant.name) {
      this.updateData()
    }
  }

  componentDidUpdate (prevProps) {
    if (this.props.tenant.name !== prevProps.tenant.name) {
      this.updateData()
    }
  }

  render () {
    const { projects } = this.state
    if (!projects) {
      return (<p>Loading...</p>)
    }

    const headerFormat = value => <Table.Heading>{value}</Table.Heading>
    const cellFormat = (value) => (
      <Table.Cell>{value}</Table.Cell>)
    const cellProjectFormat = (value) => (
      <Table.Cell>
        <Link to={this.props.tenant.linkPrefix + '/project/' + value}>
          {value}
        </Link>
      </Table.Cell>)
    const cellBuildFormat = (value) => (
      <Table.Cell>
        <Link to={this.props.tenant.linkPrefix + '/builds?project=' + value}>
          builds
        </Link>
      </Table.Cell>)
    const columns = []
    const myColumns = ['name', 'connection', 'type', 'last builds']
    myColumns.forEach(column => {
      let formatter = cellFormat
      let prop = column
      if (column === 'name') {
        formatter = cellProjectFormat
      }
      if (column === 'connection') {
        prop = 'connection_name'
      }
      if (column === 'Last builds') {
        prop = 'name'
        formatter = cellBuildFormat
      }
      columns.push({
        header: {label: column,
          formatters: [headerFormat]},
        property: prop,
        cell: {formatters: [formatter]}
      })
    })
    return (
      <Table.PfProvider
        striped
        bordered
        hover
        columns={columns}
      >
        <Table.Header/>
        <Table.Body
          rows={projects}
          rowKey="name"
        />
      </Table.PfProvider>)
  }
}

export default connect(state => ({tenant: state.tenant}))(ProjectsPage)
