// web/tenants/tenants.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { HttpClient } from '@angular/common/http'

import getSourceUrl from '../util'

@Component({
  template: require('./tenants.component.html')
})
export default class TenantsComponent implements OnInit {

  tenants: Tenant[]

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.tenantsFetch()
  }

  tenantsFetch(): void {
    this.http.get<Tenant[]>(getSourceUrl('tenants'))
      .subscribe(tenants => { this.tenants = tenants })
  }
}

<!--
Copyright 2017 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <!-- TODO(mordred) Make navigation smarter to handle tenants list -->
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Projects</th>
        <th>Jobs</th>
        <th>Builds</th>
        <th>Projects count</th>
        <th>Queue size</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let tenant of tenants">
        <td>{{ tenant.name }}</td>
        <td><a [routerLink]="['/t', tenant.name, 'status.html']">status</a></td>
        <td><a [routerLink]="['/t', tenant.name, 'projects.html']">projects</a></td>
        <td><a [routerLink]="['/t', tenant.name, 'jobs.html']">jobs</a></td>
        <td><a [routerLink]="['/t', tenant.name, 'builds.html']">builds</a></td>
        <td>{{ tenant.projects }}</td>
        <td>{{ tenant.queue }}</td>
      </tr>
    </tbody>
  </table>
</div>

// web/src/pages/tenants.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import { Link } from 'react-router-dom'
import { Table } from 'patternfly-react'

import { fetchTenants } from '../api'

class TenantsPage extends React.Component {
  constructor () {
    super()

    this.state = {
      tenants: []
    }
  }

  componentDidMount () {
    fetchTenants().then(response => {
      this.setState({tenants: response.data})
    })
  }

  render () {
    const { tenants } = this.state
    if (tenants.length === 0) {
      return (<p>Loading...</p>)
    }
    const headerFormat = value => <Table.Heading>{value}</Table.Heading>
    const cellFormat = (value) => (
      <Table.Cell>{value}</Table.Cell>)
    const columns = []
    const myColumns = ['name', 'status', 'jobs', 'builds', 'projects', 'queue']
    myColumns.forEach(column => {
      columns.push({
        header: {label: column,
          formatters: [headerFormat]},
        property: column,
        cell: {formatters: [cellFormat]}
      })
    })
    tenants.forEach(tenant => {
      tenant.status = (
        <Link to={'/t/' + tenant.name + '/status'}>Status</Link>)
      tenant.jobs = (
        <Link to={'/t/' + tenant.name + '/jobs'}>Jobs</Link>)
      tenant.builds = (
        <Link to={'/t/' + tenant.name + '/builds'}>Builds</Link>)
    })
    return (
      <Table.PfProvider
        striped
        bordered
        hover
        columns={columns}
      >
        <Table.Header/>
        <Table.Body
          rows={tenants}
          rowKey="name"
        />
      </Table.PfProvider>)
  }
}

export default TenantsPage
